// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    // ElAffix: typeof import('../packages/setaria-components')['ElAffix']
    // ElAlert: typeof import('../packages/setaria-components')['ElAlert']
    // ElAside: typeof import('../packages/setaria-components')['ElAside']
    // ElAutocomplete: typeof import('../packages/setaria-components')['ElAutocomplete']
    // ElAvatar: typeof import('../packages/setaria-components')['ElAvatar']
    // ElBacktop: typeof import('../packages/setaria-components')['ElBacktop']
    // ElBadge: typeof import('../packages/setaria-components')['ElBadge']
    // ElBreadcrumb: typeof import('../packages/setaria-components')['ElBreadcrumb']
    // ElBreadcrumbItem: typeof import('../packages/setaria-components')['ElBreadcrumbItem']
    // ElButton: typeof import('../packages/setaria-components')['ElButton']
    // ElButtonGroup: typeof import('../packages/setaria-components')['ElButtonGroup']
    // ElCalendar: typeof import('../packages/setaria-components')['ElCalendar']
    // ElCard: typeof import('../packages/setaria-components')['ElCard']
    // ElCarousel: typeof import('../packages/setaria-components')['ElCarousel']
    // ElCarouselItem: typeof import('../packages/setaria-components')['ElCarouselItem']
    // ElCascader: typeof import('../packages/setaria-components')['ElCascader']
    // ElCascaderPanel: typeof import('../packages/setaria-components')['ElCascaderPanel']
    // ElCheckbox: typeof import('../packages/setaria-components')['ElCheckbox']
    // ElCheckboxButton: typeof import('../packages/setaria-components')['ElCheckboxButton']
    // ElCheckboxGroup: typeof import('../packages/setaria-components')['ElCheckboxGroup']
    // ElCol: typeof import('../packages/setaria-components')['ElCol']
    // ElCollapse: typeof import('../packages/setaria-components')['ElCollapse']
    // ElCollapseItem: typeof import('../packages/setaria-components')['ElCollapseItem']
    // ElCollapseTransition: typeof import('../packages/setaria-components')['ElCollapseTransition']
    // ElColorPicker: typeof import('../packages/setaria-components')['ElColorPicker']
    // ElContainer: typeof import('../packages/setaria-components')['ElContainer']
    // ElConfigProvider: typeof import('../packages/setaria-components')['ElConfigProvider']
    // ElDatePicker: typeof import('../packages/setaria-components')['ElDatePicker']
    // ElDialog: typeof import('../packages/setaria-components')['ElDialog']
    // ElDivider: typeof import('../packages/setaria-components')['ElDivider']
    // ElDrawer: typeof import('../packages/setaria-components')['ElDrawer']
    // ElDropdown: typeof import('../packages/setaria-components')['ElDropdown']
    // ElDropdownItem: typeof import('../packages/setaria-components')['ElDropdownItem']
    // ElDropdownMenu: typeof import('../packages/setaria-components')['ElDropdownMenu']
    // ElEmpty: typeof import('../packages/setaria-components')['ElEmpty']
    // ScHelloWould: typeof import('../packages/setaria-components')['ScHelloWould']
    ScSchemaForm: typeof import('../packages/setaria-components')['ScSchemaForm']
    ScSearchForm: typeof import('../packages/setaria-components')['ScSearchForm']
    ScSchemaTable: typeof import('../packages/setaria-components')['ScSchemaTable']
    // ElFooter: typeof import('../packages/setaria-components')['ElFooter']
    // ElForm: typeof import('../packages/setaria-components')['ElForm']
    // ElFormItem: typeof import('../packages/setaria-components')['ElFormItem']
    // ElHeader: typeof import('../packages/setaria-components')['ElHeader']
    // ElIcon: typeof import('../packages/setaria-components')['ElIcon']
    // ElImage: typeof import('../packages/setaria-components')['ElImage']
    // ElImageViewer: typeof import('../packages/setaria-components')['ElImageViewer']
    // ElInput: typeof import('../packages/setaria-components')['ElInput']
    // ElInputNumber: typeof import('../packages/setaria-components')['ElInputNumber']
    // ElLink: typeof import('../packages/setaria-components')['ElLink']
    // ElMain: typeof import('../packages/setaria-components')['ElMain']
    // ElMenu: typeof import('../packages/setaria-components')['ElMenu']
    // ElMenuItem: typeof import('../packages/setaria-components')['ElMenuItem']
    // ElMenuItemGroup: typeof import('../packages/setaria-components')['ElMenuItemGroup']
    // ElOption: typeof import('../packages/setaria-components')['ElOption']
    // ElOptionGroup: typeof import('../packages/setaria-components')['ElOptionGroup']
    // ElPageHeader: typeof import('../packages/setaria-components')['ElPageHeader']
    // ElPagination: typeof import('../packages/setaria-components')['ElPagination']
    // ElPopconfirm: typeof import('../packages/setaria-components')['ElPopconfirm']
    // ElPopper: typeof import('../packages/setaria-components')['ElPopper']
    // ElProgress: typeof import('../packages/setaria-components')['ElProgress']
    // ElRadio: typeof import('../packages/setaria-components')['ElRadio']
    // ElRadioButton: typeof import('../packages/setaria-components')['ElRadioButton']
    // ElRadioGroup: typeof import('../packages/setaria-components')['ElRadioGroup']
    // ElRate: typeof import('../packages/setaria-components')['ElRate']
    // ElRow: typeof import('../packages/setaria-components')['ElRow']
    // ElScrollbar: typeof import('../packages/setaria-components')['ElScrollbar']
    // ElSelect: typeof import('../packages/setaria-components')['ElSelect']
    // ElSlider: typeof import('../packages/setaria-components')['ElSlider']
    // ElStep: typeof import('../packages/setaria-components')['ElStep']
    // ElSteps: typeof import('../packages/setaria-components')['ElSteps']
    // ElSubMenu: typeof import('../packages/setaria-components')['ElSubMenu']
    // ElSwitch: typeof import('../packages/setaria-components')['ElSwitch']
    // ElTabPane: typeof import('../packages/setaria-components')['ElTabPane']
    // ElTable: typeof import('../packages/setaria-components')['ElTable']
    // ElTableColumn: typeof import('../packages/setaria-components')['ElTableColumn']
    // ElTabs: typeof import('../packages/setaria-components')['ElTabs']
    // ElTag: typeof import('../packages/setaria-components')['ElTag']
    // ElText: typeof import('../packages/setaria-components')['ElText']
    // ElTimePicker: typeof import('../packages/setaria-components')['ElTimePicker']
    // ElTimeSelect: typeof import('../packages/setaria-components')['ElTimeSelect']
    // ElTimeline: typeof import('../packages/setaria-components')['ElTimeline']
    // ElTimelineItem: typeof import('../packages/setaria-components')['ElTimelineItem']
    // ElTooltip: typeof import('../packages/setaria-components')['ElTooltip']
    // ElTransfer: typeof import('../packages/setaria-components')['ElTransfer']
    // ElTree: typeof import('../packages/setaria-components')['ElTree']
    // ElTreeSelect: typeof import('../packages/setaria-components')['ElTreeSelect']
    // ElTreeV2: typeof import('../packages/setaria-components')['ElTreeV2']
    // ElUpload: typeof import('../packages/setaria-components')['ElUpload']
    // ElSpace: typeof import('../packages/setaria-components')['ElSpace']
    // ElSkeleton: typeof import('../packages/setaria-components')['ElSkeleton']
    // ElSkeletonItem: typeof import('../packages/setaria-components')['ElSkeletonItem']
    // ElStatistic: typeof import('../packages/setaria-components')['ElStatistic']
    // ElCheckTag: typeof import('../packages/setaria-components')['ElCheckTag']
    // ElDescriptions: typeof import('../packages/setaria-components')['ElDescriptions']
    // ElDescriptionsItem: typeof import('../packages/setaria-components')['ElDescriptionsItem']
    // ElResult: typeof import('../packages/setaria-components')['ElResult']
    // ElSelectV2: typeof import('../packages/setaria-components')['ElSelectV2']
    // ElWatermark: typeof import('../packages/setaria-components')['ElWatermark']
  }

  // interface ComponentCustomProperties {
  // $message: typeof import('../packages/setaria-components')['ElMessage']
  // $notify: typeof import('../packages/setaria-components')['ElNotification']
  // $msgbox: typeof import('../packages/setaria-components')['ElMessageBox']
  // $messageBox: typeof import('../packages/setaria-components')['ElMessageBox']
  // $alert: typeof import('../packages/setaria-components')['ElMessageBox']['alert']
  // $confirm: typeof import('../packages/setaria-components')['ElMessageBox']['confirm']
  // $prompt: typeof import('../packages/setaria-components')['ElMessageBox']['prompt']
  // $loading: typeof import('../packages/setaria-components')['ElLoadingService']
  // }
}

export {}
