blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://issue.setaria-components.org/
    about: The issue which is not created via https://issue.setaria-components.org/ will be closed immediately.
